name: my_generators
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  source_gen: 0.9.10+1

dev_dependencies:
  build_runner: any
