name: example_usage
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.2.0 <3.0.0'


dependencies:
  my_generators:
    path: ../my_generators
  # json_serializable: ^3.4.0

dev_dependencies:
  # test: ^1.14.4
  build_runner: ^1.0.0

  
# dependency_overrides:
#   analyzer: 0.39.14
